### ISSUE TITLE
I can't figure out how to access the research mode. Can't find the research actor anywhere. 

### ISSUE THREAD

**Issue by musamaster** [eidosmontreal/unreal-vdb#8] opened 2022-04-15 17:06 UTC
Can you provide more info on how to activate that? 

Thank you so much

**Comment by thilamb** [comment] 2022-04-15 17:13
Here is the information you are looking for:

https://github.com/eidosmontreal/unreal-vdb/blob/main/TutorialSequencer.md#step-1-create-new-actor

Let me know before I close the issue please.

**Comment by musamaster** [comment] 2022-04-15 17:30
I'm so sorry. It totally works thank you. This is really fantastic btw great work. 

I have one issue. The volumes seem to clip when they're really big and in the distance. Any ideas?

**Comment by thilamb** [comment] 2022-04-15 17:47
No worries, happy to help 😊. And thanks a lot !

Not sure if we’re speaking about the same thing, but I’ve noticed clipping
with VDB files larger than 2Go.

I’ve not noticed anything with volumes in the distance, can you share a
screenshot and repro steps ?

**Comment by musamaster** [comment] 2022-04-15 18:24
here is the issue. It's a 60mb vdb file atm so not that big. 
https://user-images.githubusercontent.com/43011459/163607024-0c7d7b8e-4978-4262-a7b7-e6b5c764f39b.mp4

The steps are simple, import the vdb drag and drop to the scene.

**Comment by thilamb** [comment] 2022-04-16 02:15
It looks like your volume is disproportionately large. Could you try a scale of .1 ? 

I’m not sure what causes the clipping still. If you can send me your vdb file, I can probably find out the cause quickly.

**Comment by thilamb** [comment] 2022-04-20 11:52
I was able to reproduce this issue. 

Unfortunately, it is on the NanoVDB API side, so there's not much I can do about it.

You could try posting an issue on their [github](https://github.com/AcademySoftwareFoundation/openvdb/issues) if you want.

Hope this is alright. Cheers

**Closed as completed by thilamb** 2022-04-20 11:52 UTC
